#!/usr/bin/env python3
"""Rebind retained native-solver evidence to a local case manifest.

The historical LightSim2Grid result contains one row per OPF scenario and
source-case identity, but its original manifest was outside the compact local
snapshot. This utility derives a minimal case manifest from those retained
rows, rewrites the evidence binding to the new manifest, and leaves the
absence of raw scenario arrays explicit. It does not create or alter solver
results.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from gridinstruct_utils import ROOT, ensure_dirs, write_json


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def build_manifest(raw: dict, raw_path: Path) -> dict:
    cases = []
    for row in raw.get("cases") or []:
        cases.append(
            {
                "case_id": row["case_id"],
                "network_model": row.get("network_model"),
                "source_model_class": row.get("source_model_class"),
                "source_case": row.get("source_case"),
                "independent_result": row.get("independent_result"),
                "comparison": row.get("comparison"),
            }
        )
    if not cases or len({row["case_id"] for row in cases}) != len(cases):
        raise ValueError("retained solver evidence must contain unique non-empty case IDs")
    return {
        "contract_version": "gridinstruct-independent-solver-case-manifest-v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "derivation": "manifest derived from retained native-source fixed-control evidence; no solver values were generated by this utility",
        "source_evidence": {"path": str(raw_path), "sha256": sha256(raw_path)},
        "solver_scope": raw.get("solver", {}).get("comparison_scope"),
        "solver": raw.get("solver"),
        "case_count": len(cases),
        "excluded_case_count": 0,
        "cases": cases,
        "raw_scenario_arrays_present": False,
        "replay_reproduction_status": "manifest_rebound_raw_scenario_arrays_external",
    }


def rebind_raw(raw: dict, raw_path: Path, manifest_path: Path) -> dict:
    rebound = copy.deepcopy(raw)
    rebound["generated_at"] = datetime.now(timezone.utc).isoformat()
    rebound["case_manifest"] = {
        "path": "metadata/independent_solver_case_manifest_v1.json",
        "sha256": sha256(manifest_path),
        "derivation": "rebound to a local manifest derived from the retained evidence rows",
    }
    rebound["binding_status"] = "local_manifest_rebound_raw_scenario_arrays_external"
    rebound["input_evidence"] = {"path": str(raw_path), "sha256": sha256(raw_path)}
    dataset_path = ROOT / "data/gridinstruct_v1.2_sd_core_en.jsonl"
    rebound["dataset_binding"] = {
        "path": "data/gridinstruct_v1.2_sd_core_en.jsonl",
        "sha256": sha256(dataset_path),
        "scope": "current released English table; fixed-control case IDs are drawn from its registered OPF scenario IDs",
    }
    return rebound


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw", default="reports/independent_solver_raw_evidence_v1.2_sd_core.json")
    parser.add_argument("--manifest", default="metadata/independent_solver_case_manifest_v1.json")
    parser.add_argument("--rebound", default="reports/independent_solver_raw_evidence_v1.2_sd_core_rebound.json")
    args = parser.parse_args()
    raw_path = ROOT / args.raw
    manifest_path = ROOT / args.manifest
    rebound_path = ROOT / args.rebound
    raw = read_json(raw_path)
    ensure_dirs(manifest_path.parent, rebound_path.parent)
    write_json(manifest_path, build_manifest(raw, raw_path))
    write_json(rebound_path, rebind_raw(raw, raw_path, manifest_path))
    print(
        json.dumps(
            {
                "case_count": len(raw.get("cases") or []),
                "manifest": str(manifest_path),
                "manifest_sha256": sha256(manifest_path),
                "rebound": str(rebound_path),
                "rebound_sha256": sha256(rebound_path),
            },
            ensure_ascii=False,
        )
    )


if __name__ == "__main__":
    main()
